#
# Makefile.bor,v 1.2 2003/12/21 10:12:20 jwillemsen Exp
#
# Makefile for building the ACE Service_Configurator examples
#

DIRS = \
        IPC-tests

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
