//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by down_client.rc
//
#define IDD_DOWN_CLIENT_DIALOG          102
#define IDR_HTML_QUICKDOWN              103
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_ITEMADD              130
#define IDB_BITMAP_BG_MAIN              131
#define IDB_BITMAP_BG_SETUP             132
#define IDD_DIALOG_SETUP                133
#define IDD_DIALOG_NOTICE               134
#define IDB_BITMAP_BTN_REFILL           135
#define IDB_BITMAP_BG_NOTICE            136
#define IDB_BITMAP_BTN_ARROW_BOTTOM     137
#define IDB_BITMAP_BTN_ARROW_DOWN       138
#define IDB_BITMAP_BTN_ARROW_TOP        139
#define IDB_BITMAP_BTN_ARROW_UP         140
#define IDB_BITMAP_BTN_DOWN_DEL         141
#define IDB_BITMAP_BTN_DONE_DEL         141
#define IDB_BITMAP_BTN_PATH             142
#define IDB_BITMAP_BTN_SELALL           143
#define IDB_BITMAP_BTN_SEL_DEL          144
#define IDB_BITMAP_BTN_SETUP            145
#define IDB_BITMAP_BTN_SETUP_CANCEL     146
#define IDB_BITMAP_BTN_SETUP_OK         147
#define IDB_BITMAP_BTN_SETUP_SERARCH    148
#define IDB_BITMAP_BTN_START            149
#define IDB_BITMAP_BTN_STOP             150
#define IDB_BITMAP_BTN_EXIT             151
#define IDB_BITMAP_BTN_MAX              152
#define IDB_BITMAP_BTN_MINIMIZE         153
#define IDB_BITMAP_CHK_PROGRAM          154
#define IDB_BITMAP_CHK_SYSTEM           155
#define IDB_BITMAP_CHK_NORMAL           156
#define IDI_ICON_BASIC_PATH             157
#define IDI_ICON_CANCEL                 158
#define IDI_ICON_CHECK                  159
#define IDI_ICON_CONTINUE               160
#define IDI_ICON_LAST_PATH              161
#define IDI_ICON_OVERWRITE              162
#define IDB_BITMAP_BTN_MAX_             163
#define IDB_BITMAP_PROGRESSBAR          164
#define IDB_BITMAP_PROGRESSBAR1         164
#define IDD_DIALOG_EXIST                165
#define IDI_ICON_SPEED                  167
#define IDB_BITMAP_BG_CONFIRM           168
#define IDB_BITMAP_BG_EXIST             169
#define IDB_BITMAP_BTN_NOTICE_CLOSE     170
#define IDB_BITMAP_CHECK_EXIST_ALL      171
#define IDB_BITMAP_BTN_CONFIRM_NO       172
#define IDB_BITMAP_BTN_CONFIRM_YES      173
#define IDB_BITMAP_BTN_EXIST_CANCEL     174
#define IDB_BITMAP_BTN_EXIST_KEEP       175
#define IDB_BITMAP_BTN_EXIST_OVERWRITE  176
#define IDB_BITMAP_CONFIRM_TITLE_1      177
#define IDB_BITMAP_CONFIRM_TITLE_2      178
#define IDB_BITMAP_CONFIRM_TITLE_3      179
#define IDB_BITMAP4                     180
#define IDB_BITMAP_CONFIRM_TITLE_4      180
#define IDB_BITMAP_CHK_CLOSE_COOKIE     181
#define IDB_BITMAP1                     182
#define IDB_BITMAP_BTN_TRAY             182
#define IDB_BITMAP_BTN_EXIT2            183
#define IDD_DIALOG_CONFIRM              184
#define IDB_BITMAP_BTN_PLAY             184
#define IDB_BITMAP_PROGRESSBAR2         185
#define IDI_ICON1                       186
#define IDI_ICON2                       187
#define IDI_ICON3                       188
#define IDI_ICON4                       189
#define IDI_ICON5                       190
#define IDI_ICON6                       191
#define IDI_ICON7                       192
#define IDI_ICON8                       193
#define IDI_ICON9                       194
#define IDI_ICON10                      195
#define IDI_ICON_FOLDER                 196
#define IDD_DIALOG1                     197
#define IDB_BITMAP_BTN_FOLDER_OPEN      198
#define IDB_BITMAP_BTN_SETUP_APPLY      199
#define IDB_BITMAP_BTN_SETUP_CLOSE      200
#define IDB_BITMAP_BTN_ALRET_RETRY      202
#define IDB_BITMAP_BTN_ALRET_JUMP       203
#define IDD_DIALOG_SLIDE                204
#define IDD_DIALOG_TRAY                 207
#define IDB_BITMAP2                     208
#define IDB_BITMAP_BG_TRAY              208
#define IDB_BITMAP_TRAY_PROGRESSBAR1    209
#define IDB_BITMAP_TRAY_PROGRESSBAR2    210
#define IDB_BITMAP_BG_SLIDE             211
#define IDB_BITMAP_BTN_QUICK_DOWN       213
#define IDR_QUICK                       230
#define IDB_BITMAP_LISTHEAD             231
#define IDR_GIF1                        232
#define IDR_SLOW                        232
#define IDC_STATIC_NOTICE_INFO          1001
#define IDC_COMBO_SETUPT_1              1004
#define IDC_COMBO_SPEED                 1005
#define IDC_COMBO_SETUPT_2              1006
#define IDC_PROGRESS1                   1006
#define IDC_COMBO_SETUPT_3              1007
#define IDC_STATIC_TIME_USE             1007
#define IDC_STATIC_EXIST                1007
#define IDC_STATIC_TIME_OVER            1008
#define IDC_STATIC_CONFIRM              1008
#define IDC_STATIC_EXIST2               1008
#define IDC_STATIC_PACKET               1009
#define IDC_STATIC_EXIST3               1009
#define IDC_LIST1                       1009
#define IDC_STATIC_FIXDATE              1010
#define IDC_PROGRESS2                   1010
#define IDC_STATIC_COUNT                1011
#define IDC_STATIC_PATH                 1011
#define IDC_STATIC_PERCENT              1012
#define IDC_STATIC_TITLE                1012
#define IDC_PROGRESS3                   1012
#define IDC_STATIC_SPEED                1013
#define IDC_STATIC1                     1013
#define IDC_STATIC_DOWNPATH             1014
#define IDC_STATIC_TEXT                 1014
#define IDC_STATIC_FILENAME             1015
#define IDC_GIFFIRST                    1016
#define MSG_ALERTWINDOW                 5000
#define MSG_LOGIN_OTHER                 5001
#define MSG_DOWNLOAD                    5002
#define MSG_PACKET_REQ                  5003
#define MSG_FILE_OVERWRITE              5004
#define MSG_FORCE_EXIT                  5006
#define MSG_DOWNEND                     5050
#define MSG_PACKET_USE                  5051
#define IDC_LISTCTRL                    10001
#define IDC_RADIO_DOWN_1                33465
#define IDC_RADIO_DOWN_2                33466
#define IDC_RADIO_DOWN_3                33467
#define IDC_RADIO_DOWN_4                33468
#define IDC_RADIO_DOWN_5                33469
#define IDC_RADIO_UP_1                  33475
#define IDC_RADIO_UP_2                  33476
#define IDC_RADIO_UP_3                  33477
#define IDC_RADIO_UP_4                  33478
#define IDC_RADIO_UP_5                  33479

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
