# -*- Makefile -*-

#----------------------------------------------------------------------------
#
# Makefile.main,v 4.2 2003/12/24 17:17:14 dhinton Exp
#
# Makefile for executable main. Part of misc Service_Configurator examples
#----------------------------------------------------------------------------

MAKEFILE = Makefile.main

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

BIN     = main

FILES	= main

SRC	= $(addsuffix .cpp,$(FILES))
OBJ	= $(addsuffix .o,$(FILES))

LDLIBS   += -lTimer

BUILD   = $(VBIN)

#----------------------------------------------------------------------------
#	Include macros and targets
#----------------------------------------------------------------------------

include	$(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include	$(ACE_ROOT)/include/makeinclude/macros.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.common.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.local.GNU

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------
