//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by up_client.rc
//
#define IDD_UP_CLIENT_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_NOTICE               129
#define IDB_BITMAP_BG_MAIN              131
#define IDB_BITMAP_ITEMADD              134
#define IDB_BITMAP_BG_SETUP             135
#define IDB_BITMAP_BTN_ARROW_BOTTOM     137
#define IDB_BITMAP_BTN_ARROW_DOWN       138
#define IDB_BITMAP_BTN_ARROW_TOP        139
#define IDB_BITMAP_BTN_ARROW_UP         140
#define IDB_BITMAP_BTN_DOWN_DEL         141
#define IDB_BITMAP_BTN_DONE_DEL         141
#define IDB_BITMAP_BTN_PATH             142
#define IDB_BITMAP_BTN_SELALL           143
#define IDB_BITMAP_BTN_SEL_DEL          144
#define IDB_BITMAP_BTN_SETUP            145
#define IDB_BITMAP_BTN_SETUP_CANCEL     146
#define IDB_BITMAP_BTN_SETUP_OK         147
#define IDB_BITMAP_BTN_SETUP_SERARCH    148
#define IDB_BITMAP_BTN_START            149
#define IDB_BITMAP_BTN_STOP             150
#define IDB_BITMAP_BTN_EXIT             151
#define IDB_BITMAP_BTN_MAX              152
#define IDB_BITMAP_BTN_MINIMIZE         153
#define IDD_DIALOG_SETUP                154
#define IDB_BITMAP_BTN_REFILL           155
#define IDB_BITMAP_BG_NOTICE            156
#define IDB_BITMAP_CHK_PROGRAM          157
#define IDB_BITMAP_CHK_SYSTEM           158
#define IDB_BITMAP_CHK_NORMAL           159
#define IDI_ICON_BASIC_PATH             160
#define IDI_ICON_CANCEL                 161
#define IDI_ICON_CHECK                  162
#define IDI_ICON_CONTINUE               163
#define IDI_ICON_LAST_PATH              164
#define IDI_ICON_OVERWRITE              165
#define IDB_BITMAP_BTN_MAX_             166
#define IDB_BITMAP_PROGRESSBAR          167
#define IDD_DIALOG_EXIST                168
#define IDI_ICON_SPEED                  170
#define IDB_BITMAP_BG_CONFIRM           171
#define IDB_BITMAP_BG_EXIST             172
#define IDB_BITMAP_BTN_CONFIRM_NO       173
#define IDB_BITMAP_BTN_EXIST_CANCEL     174
#define IDB_BITMAP_BTN_EXIST_OVERWRITE  175
#define IDB_BITMAP_BTN_NOTICE_CLOSE     176
#define IDB_BITMAP_CHECK_EXIST_ALL      177
#define IDB_BITMAP_BTN_EXIST_KEEP       178
#define IDB_BITMAP_BTN_CONFIRM_YES      179
#define IDB_BITMAP1                     180
#define IDB_BITMAP2                     181
#define IDB_BITMAP3                     182
#define IDB_BITMAP4                     183
#define IDB_BITMAP5                     184
#define IDB_BITMAP6                     185
#define IDB_BITMAP7                     186
#define IDB_BITMAP9                     188
#define IDB_BITMAP10                    189
#define IDB_BITMAP11                    190
#define IDB_BITMAP12                    191
#define IDB_BITMAP13                    192
#define IDB_BITMAP14                    193
#define IDB_BITMAP8                     207
#define IDB_BITMAP_CONFIRM_TITLE_4      207
#define IDB_BITMAP_CHK_CLOSE_COOKIE     208
#define IDB_BITMAP_CONFIRM_TITLE_1      209
#define IDB_BITMAP_CONFIRM_TITLE_2      210
#define IDB_BITMAP_CONFIRM_TITLE_3      211
#define IDB_BITMAP15                    212
#define IDB_BITMAP_BTN_TRAY             212
#define IDD_DIALOG_CONFIRM              213
#define IDB_BITMAP_BTN_EXIT2            213
#define IDB_BITMAP_BTN_PLAY             214
#define IDI_ICON1                       214
#define IDI_ICON2                       215
#define IDI_ICON3                       216
#define IDI_ICON4                       217
#define IDI_ICON5                       218
#define IDI_ICON6                       219
#define IDI_ICON7                       220
#define IDI_ICON8                       221
#define IDI_ICON9                       222
#define IDI_ICON10                      223
#define IDI_ICON11                      224
#define IDI_ICON_FOLDER                 224
#define IDB_BITMAP_PROGRESSBAR1         225
#define IDB_BITMAP_PROGRESSBAR2         226
#define IDB_BITMAP_BTN_ALRET_RETRY      228
#define IDB_BITMAP_BTN_ALRET_JUMP       229
#define IDD_DIALOG_TRAY                 230
#define IDB_BITMAP_BG_TRAY              231
#define IDD_DIALOG_SLIDE                232
#define IDB_BITMAP16                    233
#define IDB_BITMAP_BG_SLIDE             233
#define IDB_BITMAP_TRAY_PROGRESSBAR1    234
#define IDB_BITMAP_TRAY_PROGRESSBAR2    235
#define IDB_BITMAP17                    236
#define IDB_BITMAP_LISTHEAD             236
#define IDC_LISTCTRL                    1000
#define IDC_STATIC_NOTICE_INFO          1001
#define IDC_EDIT_SETUPT                 1002
#define IDC_COMBO_SETUPT_1              1004
#define IDC_COMBO_SETUPT_2              1005
#define IDC_COMBO_SPEED                 1005
#define IDC_COMBO_SETUPT_3              1006
#define IDC_PROGRESS1                   1006
#define IDC_STATIC_TIME_USE             1007
#define IDC_STATIC_TIME_OVER            1008
#define IDC_STATIC_EXIST                1008
#define IDC_STATIC_PACKET               1009
#define IDC_STATIC_CONFIRM              1009
#define IDC_STATIC_EXIST2               1009
#define IDC_STATIC_FIXDATE              1010
#define IDC_STATIC_EXIST3               1010
#define IDC_STATIC_COUNT                1011
#define IDC_STATIC_PATH                 1011
#define IDC_STATIC_TIME_USE6            1012
#define IDC_STATIC_PERCENT              1012
#define IDC_STATIC_TITLE                1012
#define IDC_PROGRESS2                   1013
#define IDC_PROGRESS3                   1014
#define IDC_STATIC_SPEED                1015
#define IDC_STATIC_TEXT                 1015
#define IDC_STATIC_FILENAME             1016
#define IDC_STATIC1                     1016
#define MSG_ALERTWINDOW                 5000
#define MSG_LOGIN_OTHER                 5001
#define MSG_UPLOAD                      5002
#define MSG_FILE_EXIST                  5004
#define MSG_LIST_ADD_EXIT               5005
#define MSG_FORCE_EXIT                  5006
#define MSG_UPCONTENTSCOMPLETE          5007
#define MSG_UPLOAD_END                  5050
#define MSG_FILE_OVERWRITE              5051
#define IDC_RADIO_DOWN_1                33465
#define IDC_RADIO_DOWN_2                33466
#define IDC_RADIO_DOWN_3                33467
#define IDC_RADIO_DOWN_4                33468
#define IDC_RADIO_DOWN_5                33469
#define IDC_RADIO_UP_1                  33475
#define IDC_RADIO_UP_2                  33476
#define IDC_RADIO_UP_3                  33477
#define IDC_RADIO_UP_4                  33478
#define IDC_RADIO_UP_5                  33479

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
