# Makefile,v 1.1 2004/01/01 21:01:00 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.

BIN = Basic Basic_Robust Iovec Server

SOURCES = $(addsuffix .cpp,$(BIN))

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
