#
# Makefile.bor,v 1.5 2003/12/21 10:12:20 jwillemsen Exp
#
# Makefile for building the Reactor examples
#

DIRS = \
        Dgram \
        Multicast \
        Ntalker \
        Proactor \
        WFMO_Reactor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
