#
# Makefile.bor,v 1.3 2003/12/21 10:12:20 jwillemsen Exp
#
# Makefile for building the RMCast Send_File ace examples
#

NAMES = \
	Receiver \
	Sender

OBJFILES = $(OBJDIR)\$(NAME).obj

CFLAGS = $(ACE_CFLAGS) $(ACE_RMCAST_CFLAGS)

CPPDIR = .

LIBFILES = $(ACE_LIB) $(ACE_RMCAST_LIB)

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
