#
# makefile.bor,v 4.2 2003/12/21 10:06:33 jwillemsen Exp
#
# Makefile for building the Misc performance-tests
#

MAKEFILES = \
	basic_perf.bor \
	childbirth_time.bor \
	context_switch_time.bor \
	preempt.bor \
	test_mutex.bor \
	test_naming.bor \
	test_singleton.bor

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>

