#
# Makefile.bor,v 1.2 2003/12/21 10:06:33 jwillemsen Exp
#
# Makefile for building the ACE Server_Concurrency performance-tests
#

DIRS = \
        Leader_Follower \
        Queue_Based_Workers

!include <$(ACE_ROOT)\include\makeinclude\recurse.bor>
